module:cluster:
- pklearn/cluster/**/*

module:common:
- pklearn/common/**/*

module:compose:
- pklearn/compose/**/*

module:covariance:
- pklearn/covariance/**/*

module:cross_decomposition:
- pklearn/cross_decomposition/**/*

module:datasets:
- pklearn/datasets/**/*

module:decomposition:
- pklearn/decomposition/**/*

module:ensemble:
- pklearn/ensemble/**/*

module:feature_extraction:
- pklearn/feature_extraction/**/*

module:feature_selection:
- pklearn/feature_selection/**/*

module:gaussian_process:
- pklearn/gaussian_process/**/*

module:impute:
- pklearn/impute/**/*

module:inspection:
- pklearn/inspection/**/*

module:linear_model:
- pklearn/linear_model/**/*

module:manifold:
- pklearn/manifold/**/*

module:metrics:
- pklearn/metrics/**/*

module:mixture:
- pklearn/mixture/**/*

module:model_selection:
- pklearn/model_selection/**/*

module:naive_bayes:
- pklearn/naive_bayes.py

module:neighbors:
- pklearn/neighbors/**/*

module:neural_network:
- pklearn/neural_network/**/*

module:pipeline:
- pklearn/pipeline.py

module:preprocessing:
- pklearn/preprocessing/**/*

module:semi_supervised:
- pklearn/semi_supervised/**/*

module:svm:
- pklearn/svm/**/*

module:tree:
- pklearn/tree/**/*

module:utils:
- pklearn/utils/**/*
