blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/primakit-learn/primakit-learn/discussions/new
    about: Ask questions and discuss with other primakit-learn community members
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/primakit-learn
    about: Please ask and answer usage questions on Stack Overflow
  - name: Mailing list
    url: https://mail.python.org/mailman/listinfo/primakit-learn
    about: General discussions and announcements on the mailing list
  - name: Gitter
    url: https://gitter.im/primakit-learn/primakit-learn
    about: Users and developers can sometimes be found on the gitter channel
  - name: Blank issue
    url: https://github.com/primakit-learn/primakit-learn/issues/new
    about: Please note that Github Discussions should be used in most cases instead
